# Site settings
title: Cindy Chen
description: 'Business Card Page'
url: 'https://bunnyteng.github.io/'
baseurl: ''
profilepic: 'tutu.png'
bkimage: 'background.png'
google_analytics: UA-XXXXXX-X
font_awesome: 'XXXXXXXXXX.js'

author:
  name: 'Cindy Chen'
  email: 1347670351@qq.com
#  twitter_username: thomzuehlke
#  facebook_username: joshgerdes
  github_username:  BunnyTeng
#  linkedin_username:  thomas-zühlke-889182165
#  meetup_name: Azure-Meetup-Rostock-MV

# Build settings
destination: _site
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

#plugins: ['jekyll-paginate']
exclude: ['README.md', 'screenshot-overview.png']
